"""
SciVizKit — Chart Registry
Central registry of all 50+ supported chart types.
"""

ALL_DOMAINS = ["General", "Biology", "Chemistry/Materials", "Medicine", "Physics", "Social Science"]

CHART_REGISTRY = {
    # ── Distribution ────────────────────────────────────────────────────
    "histogram": {
        "id": "histogram",
        "name": "Histogram",
        "category": "Distribution",
        "description": "Shows the frequency distribution of a single numeric variable.",
        "when_to_use": "Use when you want to understand the shape, spread, and central tendency of one variable.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "kde": {
        "id": "kde",
        "name": "KDE Plot",
        "category": "Distribution",
        "description": "Kernel Density Estimate — a smoothed version of the histogram.",
        "when_to_use": "Use to visualise the probability density of a continuous variable, especially for comparisons.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "violin": {
        "id": "violin",
        "name": "Violin Plot",
        "category": "Distribution",
        "description": "Combines box plot with KDE to show distribution shape per group.",
        "when_to_use": "Use when comparing distributions across multiple categories.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "boxplot": {
        "id": "boxplot",
        "name": "Box Plot",
        "category": "Distribution",
        "description": "Displays quartiles, median, and outliers of a distribution.",
        "when_to_use": "Use to compare summary statistics across groups and identify outliers.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stripplot": {
        "id": "stripplot",
        "name": "Strip Plot",
        "category": "Distribution",
        "description": "Shows individual data points along an axis, optionally grouped.",
        "when_to_use": "Use with small-to-medium datasets to show all data points alongside group structure.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "beeswarm": {
        "id": "beeswarm",
        "name": "Beeswarm Plot",
        "category": "Distribution",
        "description": "Non-overlapping strip plot showing all individual points.",
        "when_to_use": "Use when you want to see every data point without overlap, especially for small datasets.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "ecdf": {
        "id": "ecdf",
        "name": "ECDF Plot",
        "category": "Distribution",
        "description": "Empirical Cumulative Distribution Function.",
        "when_to_use": "Use to understand what fraction of data falls below a given value.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "qqplot": {
        "id": "qqplot",
        "name": "Q-Q Plot",
        "category": "Distribution",
        "description": "Quantile-Quantile plot to assess normality of a distribution.",
        "when_to_use": "Use to check if your data follows a theoretical distribution (e.g., normal).",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Comparison ───────────────────────────────────────────────────────
    "bar": {
        "id": "bar",
        "name": "Bar Chart",
        "category": "Comparison",
        "description": "Compares values across discrete categories.",
        "when_to_use": "Use to compare magnitudes of different categories.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "grouped_bar": {
        "id": "grouped_bar",
        "name": "Grouped Bar Chart",
        "category": "Comparison",
        "description": "Side-by-side bars for comparing sub-groups within categories.",
        "when_to_use": "Use to compare values across categories broken down by a second variable.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stacked_bar": {
        "id": "stacked_bar",
        "name": "Stacked Bar Chart",
        "category": "Comparison",
        "description": "Stacked bars showing part-to-whole relationships across categories.",
        "when_to_use": "Use to show composition within categories while comparing totals.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 4},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "lollipop": {
        "id": "lollipop",
        "name": "Lollipop Chart",
        "category": "Comparison",
        "description": "Cleaner alternative to bar chart with a line and dot.",
        "when_to_use": "Use when you have many categories and bar chart feels visually heavy.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "dumbbell": {
        "id": "dumbbell",
        "name": "Dumbbell Chart",
        "category": "Comparison",
        "description": "Shows change or difference between two values for each item.",
        "when_to_use": "Use to show before/after or two-condition comparisons per item.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "dotplot": {
        "id": "dotplot",
        "name": "Dot Plot",
        "category": "Comparison",
        "description": "Dots positioned along an axis for category comparisons.",
        "when_to_use": "Use as a cleaner alternative to a bar chart, especially with sorted data.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "slope": {
        "id": "slope",
        "name": "Slope Chart",
        "category": "Comparison",
        "description": "Shows change in rank or value between two time points.",
        "when_to_use": "Use to highlight change between exactly two points for multiple items.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "waterfall": {
        "id": "waterfall",
        "name": "Waterfall Chart",
        "category": "Comparison",
        "description": "Shows cumulative effect of sequential positive and negative values.",
        "when_to_use": "Use to visualise how an initial value changes step by step.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ["General", "Social Science", "Chemistry/Materials"],
        "static": True,
        "interactive": True,
    },
    "errorbar": {
        "id": "errorbar",
        "name": "Error Bar Plot",
        "category": "Comparison",
        "description": "Bar or point chart with error bars showing variability.",
        "when_to_use": "Use when you need to display measurement uncertainty or confidence intervals.",
        "requires": {"min_numeric": 2, "min_categorical": 1, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Correlation ───────────────────────────────────────────────────────
    "scatter": {
        "id": "scatter",
        "name": "Scatter Plot",
        "category": "Correlation",
        "description": "Two-dimensional relationship between two numeric variables.",
        "when_to_use": "Use to explore correlations and patterns between two continuous variables.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "bubble": {
        "id": "bubble",
        "name": "Bubble Chart",
        "category": "Correlation",
        "description": "Scatter plot with a third variable encoded as bubble size.",
        "when_to_use": "Use to show 3-4 variables simultaneously in a 2D plane.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "hexbin": {
        "id": "hexbin",
        "name": "Hexbin Plot",
        "category": "Correlation",
        "description": "Hexagonal binning for dense scatter plots.",
        "when_to_use": "Use when scatter plot has too many overlapping points (large datasets).",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 100},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "corr_heatmap": {
        "id": "corr_heatmap",
        "name": "Correlation Heatmap",
        "category": "Correlation",
        "description": "Matrix heatmap of Pearson correlation coefficients.",
        "when_to_use": "Use to quickly identify which variables are correlated in a multi-variable dataset.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "pairplot": {
        "id": "pairplot",
        "name": "Pair Plot",
        "category": "Correlation",
        "description": "Grid of scatter plots for all pairs of numeric variables.",
        "when_to_use": "Use for exploratory analysis of all pairwise relationships at once.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "parallel_coords": {
        "id": "parallel_coords",
        "name": "Parallel Coordinates",
        "category": "Correlation",
        "description": "Multi-axis plot for high-dimensional data relationships.",
        "when_to_use": "Use to detect patterns and clusters across many numeric dimensions simultaneously.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Time Series ───────────────────────────────────────────────────────
    "line": {
        "id": "line",
        "name": "Line Chart",
        "category": "Time Series",
        "description": "Classic line chart for time-ordered data.",
        "when_to_use": "Use to show trends or changes in a variable over time.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "area": {
        "id": "area",
        "name": "Area Chart",
        "category": "Time Series",
        "description": "Line chart with filled area below.",
        "when_to_use": "Use to emphasise cumulative totals or the magnitude of change over time.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "stacked_area": {
        "id": "stacked_area",
        "name": "Stacked Area Chart",
        "category": "Time Series",
        "description": "Multiple stacked area series showing composition over time.",
        "when_to_use": "Use to show how multiple variables contribute to a total over time.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "step_line": {
        "id": "step_line",
        "name": "Step Line Chart",
        "category": "Time Series",
        "description": "Step-function line chart for discrete change events.",
        "when_to_use": "Use for variables that change instantaneously (e.g., stock prices, dosage).",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 1, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Proportional ─────────────────────────────────────────────────────
    "pie": {
        "id": "pie",
        "name": "Pie Chart",
        "category": "Proportional",
        "description": "Classic circle divided into slices for part-to-whole.",
        "when_to_use": "Use sparingly, only when there are few categories and proportions differ markedly.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "donut": {
        "id": "donut",
        "name": "Donut Chart",
        "category": "Proportional",
        "description": "Pie chart with a hollow centre for labelling.",
        "when_to_use": "Use as a modern alternative to pie chart when the centre space is useful.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "treemap": {
        "id": "treemap",
        "name": "Treemap",
        "category": "Proportional",
        "description": "Hierarchical rectangles sized by value.",
        "when_to_use": "Use to show part-to-whole with many categories or hierarchical data.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "sunburst": {
        "id": "sunburst",
        "name": "Sunburst Chart",
        "category": "Proportional",
        "description": "Multi-level pie chart for hierarchical data.",
        "when_to_use": "Use for hierarchical part-to-whole data with two or more levels.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },
    "nightingale": {
        "id": "nightingale",
        "name": "Nightingale Rose Chart",
        "category": "Proportional",
        "description": "Polar bar chart (Florence Nightingale's coxcomb plot).",
        "when_to_use": "Use for cyclical or categorical data where polar representation adds clarity.",
        "requires": {"min_numeric": 1, "min_categorical": 1, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },

    # ── Network ───────────────────────────────────────────────────────────
    "sankey": {
        "id": "sankey",
        "name": "Sankey Diagram",
        "category": "Network",
        "description": "Flow diagram showing quantities between nodes.",
        "when_to_use": "Use to visualise flows, transfers, or conversions between categories.",
        "requires": {"min_numeric": 1, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": False,
        "interactive": True,
    },
    "network_graph": {
        "id": "network_graph",
        "name": "Network Graph",
        "category": "Network",
        "description": "Node-link diagram showing connections between entities.",
        "when_to_use": "Use to visualise relationships, edges, and network structure.",
        "requires": {"min_numeric": 0, "min_categorical": 2, "min_datetime": 0, "min_rows": 3},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },
    "dendrogram": {
        "id": "dendrogram",
        "name": "Dendrogram",
        "category": "Network",
        "description": "Hierarchical clustering tree diagram.",
        "when_to_use": "Use to show hierarchical clustering results of observations or features.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 5},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": False,
    },

    # ── Scientific ────────────────────────────────────────────────────────
    "volcano": {
        "id": "volcano",
        "name": "Volcano Plot",
        "category": "Scientific",
        "description": "Log fold-change vs -log10(p-value) for differential expression.",
        "when_to_use": "Use in genomics/proteomics to show statistical significance vs magnitude of change.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Biology", "Medicine"],
        "static": True,
        "interactive": True,
    },
    "pca_plot": {
        "id": "pca_plot",
        "name": "PCA Plot",
        "category": "Scientific",
        "description": "Principal Component Analysis dimensionality reduction plot.",
        "when_to_use": "Use to visualise high-dimensional data in 2D and identify clusters.",
        "requires": {"min_numeric": 3, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "roc_curve": {
        "id": "roc_curve",
        "name": "ROC Curve",
        "category": "Scientific",
        "description": "Receiver Operating Characteristic curve for classifier evaluation.",
        "when_to_use": "Use to evaluate and compare binary classification model performance.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 20},
        "domains": ["Medicine", "Biology", "General"],
        "static": True,
        "interactive": True,
    },
    "radar": {
        "id": "radar",
        "name": "Radar Chart",
        "category": "Scientific",
        "description": "Spider/web chart for multivariate comparison.",
        "when_to_use": "Use to compare items across multiple quantitative dimensions simultaneously.",
        "requires": {"min_numeric": 3, "min_categorical": 1, "min_datetime": 0, "min_rows": 2},
        "domains": ALL_DOMAINS,
        "static": True,
        "interactive": True,
    },
    "parity_plot": {
        "id": "parity_plot",
        "name": "Parity Plot",
        "category": "Scientific",
        "description": "Predicted vs actual values for model validation.",
        "when_to_use": "Use to assess how closely model predictions match experimental observations.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Chemistry/Materials", "Physics", "Medicine", "General"],
        "static": True,
        "interactive": True,
    },
    "bland_altman": {
        "id": "bland_altman",
        "name": "Bland-Altman Plot",
        "category": "Scientific",
        "description": "Agreement between two measurement methods.",
        "when_to_use": "Use to assess if two clinical or measurement methods agree sufficiently.",
        "requires": {"min_numeric": 2, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Medicine", "Biology", "General"],
        "static": True,
        "interactive": True,
    },
    "kaplan_meier": {
        "id": "kaplan_meier",
        "name": "Kaplan-Meier Curve",
        "category": "Scientific",
        "description": "Survival function estimator for time-to-event data.",
        "when_to_use": "Use for survival analysis: time-to-event outcomes in clinical or biological studies.",
        "requires": {"min_numeric": 1, "min_categorical": 0, "min_datetime": 0, "min_rows": 10},
        "domains": ["Medicine", "Biology"],
        "static": True,
        "interactive": True,
    },
}
